export const SCREEN = {
  SPLASH: 'SplashScreen',
  ANIMATION:"Animation",
  ONBOARDING:'OnBoarding',
  AUTHLANDING:"AuthLanding",
  USERTYPE:"UserType",
  LOGIN: 'LoginScreen',
  CREATENEWACCOUNT:"CreateNewAccount",
  VERIFYNO:'VerifyNumber',
  VERIFYOTP:"OtpVerify",
  ACCOUNTDETAIL:"AccountDetail",
  IDENTITYVERIFY:"IdentityVerify",
  HOMESCREEN:"HomeScreen",
  ORDERSREEN:"OrderScreen",
  ADDSCREEN:"AddScreen",
  MESSAGESCREEN:"MessageScreen",
  PROFILESCREEN:"ProfileScreen",
  EDITPROFILE:"EditProfile",
  EARNINGS:"Earnings"
};